export const CARD_BG =[
    { id: 1, bgColor: 'linear-gradient(135deg, #e5f8f3 0%, #f7fcfa 100%)'},
    { id: 2, bgColor: 'linear-gradient(135deg, #fef9e7 0%, #ffdf4 100%)'},
    { id: 3, bgColor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)'},
    { id: 4, bgColor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)'},
    { id: 5, bgColor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)'},
    { id: 6, bgColor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)'},
    { id: 7, bgColor: 'linear-gradient(135deg, #fff4fc 0%, #fffBfd 100%)'},
    { id: 8, bgColor: 'linear-gradient(135deg, #eBfef3 0%, #f5fef8 100%)'},
    { id: 9, bgColor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)'},
    { id: 10, bgColor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)'},
]

export const APP_FEATURES = [
    {
        id:"01",
        title:"Tailored Just for you",
        description:"Get interview questions and model answers based on your role, experience, and specific focus areas-no generic practice here"
    },
    {
        id:"02",
        title:"Learn at your own pace",
        description:"Expand answers only when you are ready.Dive deeper into any concept instantly with AI-powered detailed explanations."
    },
    {
        id:"03",
        title:"Capture Your INsights",
        description:"Add personal notes to any question and pin important ones to the top-making yourlearning more organised and impactful."
    },
    {
        id:"04",
        title:"Understand the 'Why' Behind Answers",
        description:"Beyond just answers-unlock detailed concept explanations generated by AI helping you truly master each topic."
    },
    {
        id:"05",
        title:"Save, Oragnize, and Revisit",
        description:"Easily save your interview sets, organize them neatly in your dashboard and pick up your prepration right where you left off."
    }
]